### ISSUE TITLE
[BUG] v0.1.7 - Character selection dropdown results in Lua error

### ISSUE THREAD

**Issue by keflatbn** [peti446/CompanionsTracker#10]
**Describe the bug**
Selecting characters in dropdown results in lua error. 

**To Reproduce**
![image](https://github.com/user-attachments/assets/85f88205-aece-42be-94a1-c870279a6bbc)

**Addon version:**
- Version 0.1.7

**Lua eror (if any):**
<1x ...rfaceCompanionsTracker/GUI/OverviewFrame.lua:260: attempt to index field 'owner' (a nil value)
[string "@CompanionsTracker/GUI/OverviewFrame.lua"]:260: in function `func'
[string "@Blizzard_FrameXML/Mainline/NavigationBar.lua"]:298: in function <Blizzard_FrameXML/Mainline/NavigationBar.lua:294>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_Menu/Menu.lua"]:854: in function `Pick'
[string "@Blizzard_Menu/MenuTemplates.lua"]:64: in function <Blizzard_Menu/MenuTemplates.lua:58>

Locals:
self = Button {
 menuPointX = 0
 Event = <table> {
 }
 intrinsic = "DropdownButton"
 Art = Texture {
 }
 callbackTables = <table> {
 }
 menuRelativePoint = "BOTTOMLEFT"
 menuPointY = 0
 menuDescription = <table> {
 }
 menuAnchor = <table> {
 }
 PushedTexture = Texture {
 }
 NormalTexture = Texture {
 }
 menuPoint = "TOPLEFT"
 menu = Frame {
 }
}
id = "Ratbull-Deathwing"
_navNar = Frame {
 overlay = Frame {
 }
 template = "NavButtonTemplate"
 homeButton = TopHomeButton {
 }
 overflowButton = TopOverflowButton {
 }
 navList = <table> {
 }
 KioskOverlay = Frame {
 }
 freeButtons = <table> {
 }
 widthBuffer = 20
 home = TopHomeButton {
 }
 overflow = TopOverflowButton {
 }
}
(*temporary) = <table> {
 characterListFrame = Frame {
 }
 tabsData = <table> {
 }
 expanionBackground = Texture {
 }
 base = <table> {
 }
 AceGUIWidgetVersion = 1
 buttonsFrameGroup = <table> {
 }
 localstatus = <table> {
 }
 content = Frame {
 }
 missionsTabGroup = <table> {
 }
 userdata = <table> {
 }
 scrollFrame = <table> {
 }
 type = "ExpansionOverviewFrame"
 events = <table> {
 }
 children = <table> {
 }
 subFrameRenderFrame = <table> {
 }
 expansionTitle = FontString {
 }
 navBar = Frame {
 }
 frame = CompanionsTrackerExpansionOverviewFrame1 {
 }
 selectedTab = 9
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'owner' (a nil value)"
frame = <table> {
 characterListFrame = Frame {
 }
 tabsData = <table> {
 }
 expanionBackground = Texture {
 }
 base = <table> {
 }
 AceGUIWidgetVersion = 1
 buttonsFrameGroup = <table> {
 }
 localstatus = <table> {
 }
 content = Frame {
 }
 missionsTabGroup = <table> {
 }
 userdata = <table> {
 }
 scrollFrame = <table> {
 }
 type = "ExpansionOverviewFrame"
 events = <table> {
 }
 children = <table> {
 }
 subFrameRenderFrame = <table> {
 }
 expansionTitle = FontString {
 }
 navBar = Frame {
 }
 frame = CompanionsTrackerExpansionOverviewFrame1 {
 }
 selectedTab = 9
}
>

**Comment by peti446** [comment]
Is this the top character dropdown ?

**Comment by peti446** [comment]
Will get a patch over the weekend, worked last night mmm IF you find anything else post them here sorry for all these errors ):!

**Comment by keflatbn** [comment]
Yes its the top bar character selection. Its not a big deal, if I use the tiles to select characters everything works perfectly :)
Dont stress, just super thankful you put the effort to update <3

**Comment by keflatbn** [comment]
Works perfectly, thanks again for the fast solve!
