### ISSUE TITLE
[BUG] Character dropdown results in lua error

### ISSUE THREAD

**Issue by keflatbn** [peti446/CompanionsTracker#8]
**Describe the bug**
In the addon when viewing a main window from for example shadowlands, trying to change character in the top banner dropdown results in lua error

**To Reproduce**
In addon try to switch characters in the dropdown menu

**Addon version:**
- Version 10.2.5

**Lua eror (if any):**
<1x ...rfaceCompanionsTracker/GUI/OverviewFrame.lua:260: attempt to index field 'owner' (a nil value)
[string "@CompanionsTracker/GUI/OverviewFrame.lua"]:260: in function `func'
[string "@Blizzard_FrameXML/Mainline/NavigationBar.lua"]:298: in function <Blizzard_FrameXML/Mainline/NavigationBar.lua:294>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_Menu/Menu.lua"]:854: in function `Pick'
[string "@Blizzard_Menu/MenuTemplates.lua"]:64: in function <Blizzard_Menu/MenuTemplates.lua:58>

Locals:
self = Button {
 menuPointX = 0
 Event = <table> {
 }
 intrinsic = "DropdownButton"
 Art = Texture {
 }
 callbackTables = <table> {>

**Comment by peti446** [comment]
I see you have serveral errors regarding the same, can you give me a list of active addons to maybe check any incompatibilities? ALso I would suggest you reinstall the addon itself maybe something did go wrong.

**Comment by keflatbn** [comment]
Hi, thanks for a quick feedback! 
I removed all other addons except for the buggrabber and your addon.
I do not get an error with the minimap button anymore, but when I use the dropdown to select another character I get this error:

`1x ...rfaceCompanionsTracker/GUI/OverviewFrame.lua:260: attempt to index field 'owner' (a nil value)
[string "@CompanionsTracker/GUI/OverviewFrame.lua"]:260: in function `func'
[string "@Blizzard_FrameXML/Mainline/NavigationBar.lua"]:298: in function <Blizzard_FrameXML/Mainline/NavigationBar.lua:294>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_Menu/Menu.lua"]:854: in function `Pick'
[string "@Blizzard_Menu/MenuTemplates.lua"]:64: in function <Blizzard_Menu/MenuTemplates.lua:58>

Locals:
self = Button {
 menuPointX = 0
 Event = <table> {
 }
 intrinsic = "DropdownButton"
 Art = Texture {
 }
 callbackTables = <table> {
 }
 menuRelativePoint = "BOTTOMLEFT"
 menuPointY = 0
 menuDescription = <table> {
 }
 menuAnchor = <table> {
 }
 PushedTexture = Texture {
 }
 NormalTexture = Texture {
 }
 menuPoint = "TOPLEFT"
 menu = Frame {
 }
}
id = "Ratbull-Deathwing"
_navNar = Frame {
 overlay = Frame {
 }
 template = "NavButtonTemplate"
 homeButton = TopHomeButton {
 }
 overflowButton = TopOverflowButton {
 }
 navList = <table> {
 }
 KioskOverlay = Frame {
 }
 freeButtons = <table> {
 }
 widthBuffer = 20
 home = TopHomeButton {
 }
 overflow = TopOverflowButton {
 }
}
(*temporary) = <table> {
 characterListFrame = Frame {
 }
 tabsData = <table> {
 }
 expanionBackground = Texture {
 }
 base = <table> {
 }
 AceGUIWidgetVersion = 1
 buttonsFrameGroup = <table> {
 }
 localstatus = <table> {
 }
 content = Frame {
 }
 missionsTabGroup = <table> {
 }
 userdata = <table> {
 }
 scrollFrame = <table> {
 }
 type = "ExpansionOverviewFrame"
 events = <table> {
 }
 children = <table> {
 }
 subFrameRenderFrame = <table> {
 }
 expansionTitle = FontString {
 }
 navBar = Frame {
 }
 frame = CompanionsTrackerExpansionOverviewFrame1 {
 }
 selectedTab = 111
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'owner' (a nil value)"
frame = <table> {
 characterListFrame = Frame {
 }
 tabsData = <table> {
 }
 expanionBackground = Texture {
 }
 base = <table> {
 }
 AceGUIWidgetVersion = 1
 buttonsFrameGroup = <table> {
 }
 localstatus = <table> {
 }
 content = Frame {
 }
 missionsTabGroup = <table> {
 }
 userdata = <table> {
 }
 scrollFrame = <table> {
 }
 type = "ExpansionOverviewFrame"
 events = <table> {
 }
 children = <table> {
 }
 subFrameRenderFrame = <table> {
 }
 expansionTitle = FontString {
 }
 navBar = Frame {
 }
 frame = CompanionsTrackerExpansionOverviewFrame1 {
 }
 selectedTab = 111
}
`

![image](https://github.com/user-attachments/assets/02eeb674-4317-496a-a17d-9257e2538828)

**Comment by keflatbn** [comment]
If I click from In Progress tab to Available I get this error:

`1x ...acker/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-Label.lua:151: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
[string "=[C]"]: in function `SetJustifyV'
[string "@CompanionsTracker/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-Label.lua"]:151: in function `SetJustifyV'
[string "@CompanionsTracker/GUI/OverviewFrame.lua"]:124: in function <...rfaceCompanionsTracker/GUI/OverviewFrame.lua:74>
[string "=[C]"]: ?
[string "@CompanionsTracker/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...Ons/CompanionsTracker/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@CompanionsTracker/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@CompanionsTracker/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@CompanionsTracker/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:200: in function <...Libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua:197>

Locals:
(*temporary) = FontString {
}
(*temporary) = "CENTER"
`

![image](https://github.com/user-attachments/assets/b67a7c0e-ad52-4629-823b-97c3f6ba76b6)

**Comment by keflatbn** [comment]
I see you have dependencies defined on your page, sorry if I'm totally stupid here, but do I need to download those too? I read the Embedded Library as they where included in the code?

![image](https://github.com/user-attachments/assets/476a9ca5-542a-451e-8f33-05ff82783bed)

**Comment by peti446** [comment]
No need to install the dependencies, they install themselves. I was able to reproduce the error on my end will look into it over the days ^^ It seems an issue of the dependencies, maybe it's just a case of updating them. Will let you know once I have an update

**Comment by peti446** [comment]
As reference it linked to https://github.com/peti446/CompanionsTracker/issues/7 and https://github.com/peti446/CompanionsTracker/issues/6 all same issues regarding ACE GUI/Options GUI

**Comment by peti446** [comment]
@keflatbn Got a dev version up here https://github.com/peti446/CompanionsTracker/actions/runs/10176251854/artifacts/1759003806 that should solve some dependencies but I have not tested it yet, will test it in depth tonight ^^

**Comment by keflatbn** [comment]
Tried the dev version, still same lua errors selecting character and switching tabs.

**Comment by peti446** [comment]
Okey thanks, I will get this fixed in the next couple of days
